#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use php\project\lvl2\src\Differ;

$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help                     Show this screen
  -v --version                  Show version
  --format <fmt>                Report format [default: stylish]
DOC;

//echo "\n-------1--------\n";

$params = array(
    'argv'=>array_slice($_SERVER['argv'], 1),
    'help'=>true,
    'version'=>null,
    'optionsFirst'=>false,
);

$argsArray = $params['argv'];
$formatName = '';
$pathToFile1 = '';
$pathToFile2 = '';

if ($argsArray[0] === "--format" || $argsArray[0] === "--f") {
  $formatName = $argsArray[1];
  $pathToFile1 = $argsArray[2];//"./../testFiles/file1.json";
  $pathToFile2 = $argsArray[3];//"./../testFiles/file2.json";
} else {
  $formatName = '';
  $pathToFile1 = $argsArray[0];
  $pathToFile2 = $argsArray[1];
}


$outputString = Differ\genDiff($pathToFile1, $pathToFile2, $formatName);

echo $outputString;

$valueToCheck = <<<VAL
{\n
  app_1  | -    common: {\n
  app_1  | -      + follow: false\n
  app_1  | -        setting1: Value 1\n
  app_1  | -      - setting2: 200\n
  app_1  | -      - setting3: true\n
  app_1  | -      + setting3: {\n
  app_1  | -            key: value\n
  app_1  | -        }\n
VAL;

echo "\n----------1-----------\n";
return $valueToCheck;
echo "\n----------2-----------\n";
return $outputString;

$args = Docopt::handle($doc, $params);
