name: PHP CI
on:
    - push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Test & publish code coverage
                uses: paambaati/codeclimate-action@v2.7.5
                env:
                    CC_TEST_REPORTER_ID: 433db4745bebadde1699ced55e0c7da80b0bad17c6d54aa319399e8fb90768ea
                with:
                coverageCommand: npm run coverage
                debug: true